#!/bin/sh
set -e

PARAMETERS_FILE='/var/www/html/app/config/parameters.php'

mkparameters > $PARAMETERS_FILE
chown -R www-data:www-data /var/www/html/{app,web}

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"