#!/usr/bin/env php
<?php

require_once '/var/www/html/vendor/autoload.php';

$TEMPLATE_PATH = '/usr/local/bin';
$TEMPLATE_FILE = 'parameters.template';

$loader = new Twig_Loader_Filesystem($TEMPLATE_PATH);
$twig = new Twig_Environment($loader, array('cache' => '/tmp'));

$template = $twig->load($TEMPLATE_FILE);

$values = array(
    'PARTKEEPR_AUTHENTICATION_PROVIDER' => getenv('PARTKEEPR_AUTHENTICATION_PROVIDER'),
    'PARTKEEPR_DATABASE_HOST'           => getenv('PARTKEEPR_DATABASE_HOST'),
    'PARTKEEPR_DATABASE_NAME'           => getenv('PARTKEEPR_DATABASE_NAME'),
    'PARTKEEPR_DATABASE_PORT'           => getenv('PARTKEEPR_DATABASE_PORT'),
    'PARTKEEPR_DATABASE_USER'           => getenv('PARTKEEPR_DATABASE_USER'),
    'PARTKEEPR_DATABASE_PASS'           => getenv('PARTKEEPR_DATABASE_PASS'),
    'PARTKEEPR_OKTOPART_APIKEY'         => getenv('PARTKEEPR_OKTOPART_APIKEY'),
    'PARTKEEPR_SECRET'                  => getenv('PARTKEEPR_SECRET')
);

echo $template->render($values);
?>
